---
name: amtools
version: "{{major}}.{{minor}}.{{patch}}"
description: amber's tools
entry: {{entry}}
requirements:
  - vcorelib
  - pypdf
dev_requirements:
  - setuptools-wrapper
  - types-setuptools
commands:
  - name: pdf
    description: "Dissecting PDFs"
